// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Cnet.iOS
{
	public partial class DSLCalendarView : UIView
	{
		public DSLCalendarView (IntPtr handle) : base (handle)
		{
		}
	}
}
