// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Cnt.API;
using Cnt.API.Exceptions;

namespace Cnet.iOS
{
	public partial class OSLoginViewController : UIViewController
	{
		public OSLoginViewController (IntPtr handle) : base (handle)
		{
		}

		partial void loginButtonClick(UIButton sender)
		{
			try
			{
				string deviceId = UIDevice.CurrentDevice.IdentifierForVendor.AsString();
				Client client = new Client(this.tbxUsername.Text, this.tbxPassword.Text);
				client.AuthenticateService.Authenticate(deviceId);
			}
			catch (CntResponseException) { }
		}
	}
}
