// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Drawing;
using MonoTouch.ObjCRuntime;

namespace Cnet.iOS
{
	public partial class OSNotificationsView : UIView
	{
		public OSNotificationsView () {	this.Initialize (); }
		public OSNotificationsView (IntPtr handle) : base (handle)
		{
			this.Initialize ();
		}
		public OSNotificationsView (RectangleF frame) : base (frame)
		{
			this.Initialize ();
		}

		private void Initialize ()
		{
			var arr = NSBundle.MainBundle.LoadNib("OSNotificationsView", this, null);
			var v = Runtime.GetNSObject(arr.ValueAt(0)) as UIView;
			v.Frame = new RectangleF(0, 0, Frame.Width, Frame.Height);
			AddSubview(v);

			testLabel.Text = "Messages";
		}
//		public override void Draw (System.Drawing.RectangleF rect)
//		{
//			base.Draw (rect);
//		}
	}
}
