// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Cnt.API;
using Cnt.API.Exceptions;

namespace Cnet.iOS
{
	public partial class OSViewController : UIViewController
	{
		public OSViewController (IntPtr handle) : base (handle)
		{
		}

		partial void loginButtonClick(UIButton sender)
		{
			try
			{
				Client client = new Client(null, null);
				client.AuthenticateService.Authenticate(0);
			}
			catch (CntResponseException ex) { }
		}
	}
}
