// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Cnet.iOS
{
	public partial class OSAboutUsViewController : UIViewController
	{
		public OSAboutUsViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			visitWebsiteButton.TouchUpInside += (object sender, EventArgs e) => Utility.OpenUrl("http://www.collegenanniesandtutors.com");
		}
	}
}
