// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Cnet.iOS
{
	public partial class OSAvailabilityDatesCell : UITableViewCell
	{
		public OSAvailabilityDatesCell (IntPtr handle) : base (handle)
		{
		}

		public UIButton StartButton { get { return startButton; } set { startButton = value; } }
		public UILabel StartLabel { get { return startLabel; } set { startLabel = value; } }
		public UIButton EndButton { get { return endButton; } set { endButton = value; } }
		public UILabel EndLabel { get { return endLabel; } set { endLabel = value; } }
		public UIButton SundayButton { get { return sundayButton; } set { sundayButton = value; } }
		public UIButton MondayButton { get { return mondayButton; } set { mondayButton = value; } }
		public UIButton TuesdayButton { get { return tuesdayButton; } set { tuesdayButton = value; } }
		public UIButton WednesdayButton { get { return wednesdayButton; } set { wednesdayButton = value; } }
		public UIButton ThursdayButton { get { return thursdayButton; } set { thursdayButton = value; } }
		public UIButton FridayButton { get { return fridayButton; } set { fridayButton = value; } }
		public UIButton SaturdayButton { get { return saturdayButton; } set { saturdayButton = value; } }
	}
}
