// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Cnet.iOS
{
	public partial class OSAvailabilityCell : UITableViewCell
	{
		public OSAvailabilityCell (IntPtr handle) : base (handle)
		{
		}

		public int RowIndex { get; set; }
		public UILabel DatesLabel { get { return datesLabel; } set { datesLabel = value; } }
		public UILabel TimesLabel { get { return timesLabel; } set { timesLabel = value; } }
		public UILabel DaysOfWeek { get { return daysOfWeekLabel; } set { daysOfWeekLabel = value; } }
		public UIButton EditButton { get { return editButton; } set { editButton = value; } }
		public UIButton CloseButton { get { return closeButton; } set { closeButton = value; } }
	}
}
