// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Cnet.iOS
{
	public partial class OSAvailabilityTimesCell : UITableViewCell
	{
		public OSAvailabilityTimesCell (IntPtr handle) : base (handle)
		{
		}

		public UILabel StartTimeLabel { get { return startTimeLabel; } set { startTimeLabel = value; } }
		public UILabel EndTimeLabel { get { return endTimeLabel; } set { endTimeLabel = value; } }
		public UIButton StartTimeButton { get { return startTimeButton; } set { startTimeButton = value; } }
		public UIButton StartTimeUpButton { get { return startTimeUpButton; } set { startTimeUpButton = value; } }
		public UIButton StartTimeDownButton { get { return startTimeDownButton; } set { startTimeDownButton = value; } }
		public UIButton EndTimeButton { get { return endTimeButton; } set { endTimeButton = value; } }
		public UIButton EndTimeUpButton { get { return endTimeUpButton; } set { endTimeUpButton = value; } }
		public UIButton EndTimeDownButton { get { return endTimeDownButton; } set { endTimeDownButton = value; } }
	}
}
