// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Cnet.iOS
{
	public partial class OSCalendarAppointmentCell : UITableViewCell
	{
		public OSCalendarAppointmentCell (IntPtr handle) : base (handle)
		{
		}

		public UILabel FamilyNameLabel { get { return familyNameLabel; } set { familyNameLabel = value; } }
		public UILabel StartTimeLabel { get { return startTimeLabel; } set { startTimeLabel = value; } }
		public UILabel StartTimePmLabel { get { return startTimePmLabel; } set { startTimePmLabel = value; } }
		public UILabel EndTimeLabel { get { return endTimeLabel; } set { endTimeLabel = value; } }
		public UILabel EndTimePmLabel { get { return endTimePmLabel; } set { endTimePmLabel = value; } }
		public UILabel StatusLabel { get { return statusLabel; } set { statusLabel = value; } }
		public UIImageView ProfileImage { get { return profileImage; } set { profileImage = value; } }
		public UIImageView ProfileBorderImage { get { return profileBorderImage; } set { profileBorderImage = value; } }
		public UIImageView FlagImage { get { return flagImage; } set { flagImage = value; } }
		public UIImageView StatusImage { get { return statusImage; } set { statusImage = value; } }
	}
}
