// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Cnet.iOS
{
	public partial class OSChildrenCell : UITableViewCell
	{
		public OSChildrenCell (IntPtr handle) : base (handle)
		{
		}

		public UILabel ChildrenLabel { get { return childrenLabel; } set { childrenLabel = value; } }
	}
}
