// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Cnet.iOS
{
	public partial class OSContactUsCell : UITableViewCell
	{
		public OSContactUsCell (IntPtr handle) : base (handle)
		{
		}

		public UILabel NameLabel { get { return nameLabel; } set { nameLabel = value; } }
		public UILabel AddressLabel { get { return addressLabel; } set { addressLabel = value; } }
		public UILabel PhoneLabel { get { return phoneLabel; } set { phoneLabel = value; } }
		public UILabel FaxLabel { get { return faxLabel; } set { faxLabel = value; } }
		public UILabel EmailLabel { get { return emailLabel; } set { emailLabel = value; } }
	}
}
