// This file has been autogenerated from a class added in the UI designer.

using System;

using System.Collections.Generic;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Cnt.Web.API.Models;
using Cnt.API;
using System.Linq;

namespace Cnet.iOS
{
	public partial class OSContactUsViewController : UIViewController
	{
		private List<Office> offices;

		public OSContactUsViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			LoadOffices ();
			RenderOffices ();
		}

		#region Private Methods
		private void LoadOffices()
		{
			Client client = AuthenticationHelper.GetClient();
			offices = new List<Office>(client.OfficeService.GetOffices ());
		}

		private void RenderOffices ()
		{
			string officeUrl = "http://collegenanniesandtutors.com";
			if (offices.Count < 2) {
				officesTable.Bounces = false;
				officeUrl = offices [0].Website;
			}

			officesTable.Source = new OSOfficesTableSrouce (this);

			visitWebsiteButton.TouchUpInside += (object sender, EventArgs e) => Utility.OpenUrl(officeUrl);
		}
		#endregion

		private class OSOfficesTableSrouce : UITableViewSource
		{
			#region Private Members
			private OSContactUsViewController controller;
			private static NSString OSContactUsCellId = new NSString ("ContactUsCellIdentifier");
			#endregion

			public OSOfficesTableSrouce(OSContactUsViewController parent)
			{
				controller = parent;
			}

			#region Public Methods
			public override int RowsInSection (UITableView tableview, int section)
			{
				return controller.offices.Count;
			}

			public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
			{
				OSContactUsCell cell = (OSContactUsCell)tableView.DequeueReusableCell (OSContactUsCellId, indexPath);

				Office office = controller.offices [indexPath.Row];
				cell.NameLabel.Text = office.Name;
				cell.AddressLabel.Text = office.Address.ToLocationString ("{0}\n{2}, {3} {4}");
				cell.PhoneLabel.Text = office.Phone;
				cell.FaxLabel.Text = office.Fax;
				cell.EmailLabel.Text = office.Email;
				// TODO: Handle click events on phone and email.

				return cell;
			}
			#endregion
		}
	}
}
