// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Cnet.iOS
{
	public partial class OSDetailsCell : UITableViewCell
	{
		public OSDetailsCell (IntPtr handle) : base (handle)
		{
		}

		public UILabel OrderNotesHeaderLabel { get { return orderNotesHeaderLabel; } set { orderNotesHeaderLabel = value; } }
		public UILabel OrderNotesLabel { get { return orderNotesLabel; } set { orderNotesLabel = value; } }
		public UILabel ImportantDetailsHeaderLabel { get { return importantDetailsHeaderLabel; } set { importantDetailsHeaderLabel = value; } }
		public UILabel ImportantDetailsLabel { get { return importantDetailsLabel; } set { importantDetailsLabel = value; } }
	}
}
