// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Cnet.iOS
{
	public partial class OSFamilyCell : UITableViewCell
	{
		public OSFamilyCell (IntPtr handle) : base (handle)
		{
		}

		public UIButton CallButton { get { return callButton; } set { callButton = value; } }
		public UILabel FamilyNameLabel { get { return familyNameLabel; } set { familyNameLabel = value; } }
		public UIImageView InfoImage { get { return infoImage; } set { infoImage = value; } }
		public UIImageView ProfileImage { get { return profileImage; } set { profileImage = value; } }
		public UILabel StatusLabel { get { return statusLabel; } set { statusLabel = value; } }
	}
}
