// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Cnet.iOS
{
	public partial class OSInfoCell : UITableViewCell
	{
		public OSInfoCell (IntPtr handle) : base (handle)
		{
		}

		public UILabel InfoLabel { get { return infoLabel; } set { infoLabel = value; } }
	}
}
