// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Cnet.iOS
{
	public partial class OSLocationCell : UITableViewCell
	{
		public OSLocationCell (IntPtr handle) : base (handle)
		{
		}
	}
}
