// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.UIKit;
using Cnt.API.Exceptions;

namespace Cnet.iOS
{
	public partial class OSLoginViewController : UIViewController
	{
		public OSLoginViewController (IntPtr handle) : base (handle)
		{
		}

		partial void loginButtonClick(UIButton sender)
		{
			try
			{
				string username = this.tbxUsername.Text;
				string password = this.tbxPassword.Text;
				AuthenticationHelper.Authenticate(username, password);
			}
			catch (CntResponseException ex) { }
		}
	}
}
