// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Cnt.API;
using Cnt.API.Exceptions;
using Cnt.Web.API.Models;
using System.Drawing;
using Cnt.API.Utils;

namespace Cnet.iOS
{
	// TODO: Figure out timezone stuff.
	public partial class OSNewTimesheetViewController : UIViewController
	{
		#region Private Members
		private static NSString timesheetListSegueName = new NSString ("TimesheetList");
		private const string dateFormat = "ddd, MMM d, yyyy";
		private const string timeFormat = "h:mm tt";
		private Timesheet timesheet;
		private bool hasErrors;
		#endregion

		public DateTime Start { get; set; }
		public DateTime End { get; set; }
		public string Remarks { get; set; }
		public int PlacementId { get; set; }
		public int TimesheetId { get; set; }

		public OSNewTimesheetViewController (IntPtr handle) : base (handle)
		{
		}

		#region Public Methods
		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			LoadTimesheet ();
			WireUpView ();
			RenderTimesheet ();
			SetUpKeyboardNotifications ();
		}

		public override bool ShouldPerformSegue (string segueIdentifier, NSObject sender)
		{
			if (segueIdentifier == timesheetListSegueName)
				return !hasErrors;

			return base.ShouldPerformSegue (segueIdentifier, sender);
		}
		#endregion

		#region Event Delegates
		private void ActionButtonClicked (object sender, EventArgs e)
		{
			SubmitForm ();
			if (!hasErrors)
				PerformSegue (timesheetListSegueName, this);
		}

		private void EndButtonClicked (object sender, EventArgs e)
		{
			ShowDatePicker (timesheet.End, UIDatePickerMode.Date, (object s, EventArgs ev) => {
				DateTime date = DateTime.SpecifyKind ((s as UIDatePicker).Date, DateTimeKind.Unspecified);
				timesheet.End = date;
				endLabel.Text = date.ToString (dateFormat);
			});
		}

		private void EndTimeClicked (object sender, EventArgs e)
		{
			ShowDatePicker (timesheet.End, UIDatePickerMode.Time, (object s, EventArgs ev) => {
				DateTime date = DateTime.SpecifyKind ((s as UIDatePicker).Date, DateTimeKind.Unspecified);
				TimeSpan time = new TimeSpan (date.Hour, date.Minute, date.Second);
				timesheet.End = timesheet.End.Date + time;
				endTimeLabel.Text = date.ToString (timeFormat);
			});
		}

		private void EndTimeDownClicked (object sender, EventArgs e)
		{
			DateTime date = DateTime.ParseExact (endTimeLabel.Text, timeFormat, null).AddMinutes (-15);
			TimeSpan time = new TimeSpan (date.Hour, date.Minute, date.Second);
			timesheet.End = timesheet.End.Date + time;
			endTimeLabel.Text = date.ToString (timeFormat);
		}

		private void EndTimeUpClicked (object sender, EventArgs e)
		{
			DateTime date = DateTime.ParseExact (endTimeLabel.Text, timeFormat, null).AddMinutes (15);
			TimeSpan time = new TimeSpan (date.Hour, date.Minute, date.Second);
			timesheet.End = timesheet.End.Date + time;
			endTimeLabel.Text = date.ToString (timeFormat);
		}

		private void ResetButtonClicked (object sender, EventArgs e)
		{
			ResetForm ();
		}

		private void StartButtonClicked (object sender, EventArgs e)
		{
			ShowDatePicker (timesheet.Start, UIDatePickerMode.Date, (object s, EventArgs ev) => {
				DateTime date = DateTime.SpecifyKind ((s as UIDatePicker).Date, DateTimeKind.Unspecified);
				timesheet.Start = date;
				startLabel.Text = date.ToString (dateFormat);
			});
		}

		private void StartTimeClicked (object sender, EventArgs e)
		{
			ShowDatePicker (timesheet.Start, UIDatePickerMode.Time, (object s, EventArgs ev) => {
				DateTime date = DateTime.SpecifyKind ((s as UIDatePicker).Date, DateTimeKind.Unspecified);
				TimeSpan time = new TimeSpan (date.Hour, date.Minute, date.Second);
				timesheet.Start = timesheet.Start.Date + time;
				startTimeLabel.Text = date.ToString (timeFormat);
			});
		}

		private void StartTimeDownClicked (object sender, EventArgs e)
		{
			DateTime date = DateTime.ParseExact (startTimeLabel.Text, timeFormat, null).AddMinutes (-15);
			TimeSpan time = new TimeSpan (date.Hour, date.Minute, date.Second);
			timesheet.Start = timesheet.Start.Date + time;
			startTimeLabel.Text = date.ToString (timeFormat);
		}

		private void StartTimeUpClicked (object sender, EventArgs e)
		{
			DateTime date = DateTime.ParseExact (startTimeLabel.Text, timeFormat, null).AddMinutes (15);
			TimeSpan time = new TimeSpan (date.Hour, date.Minute, date.Second);
			timesheet.Start = timesheet.Start.Date + time;
			startTimeLabel.Text = date.ToString (timeFormat);
		}
		#endregion

		#region Private Methods
		private void LoadTimesheet ()
		{
			if (TimesheetId > 0) {
				try {
					Client client = AuthenticationHelper.GetClient ();
					timesheet = client.TimesheetService.GetTimesheet (TimesheetId);
				} catch (CntResponseException ex) {
					Utility.ShowError (ex);
				}
			} else {
				timesheet = new Timesheet () { 
					Created = DateTime.Now,
					Start = Start.RoundToNearest (TimeSpan.FromMinutes (15)),
					End = End.RoundToNearest (TimeSpan.FromMinutes (15)),
					Description = Remarks,
					PlacementId = PlacementId
				};
			}
		}

		private void RenderTimesheet ()
		{
			DateTime localStart = timesheet.Start;
			DateTime localEnd = timesheet.End;
			startLabel.Text = localStart.ToString (dateFormat);
			endLabel.Text = localEnd.ToString (dateFormat);
			startTimeLabel.Text = localStart.ToString (timeFormat);
			endTimeLabel.Text = localEnd.ToString (timeFormat);
			recapTextView.Text = timesheet.Description;
		}

		private void ResetForm ()
		{
			timesheet.Start = Start.RoundToNearest (TimeSpan.FromMinutes (15));
			timesheet.End = End.RoundToNearest (TimeSpan.FromMinutes (15));
			timesheet.Description = Remarks;
			RenderTimesheet ();
		}

		private void ShowDatePicker(DateTime date, UIDatePickerMode mode, EventHandler valueChangedHandler)
		{
			var actionSheetDatePicker = new ActionSheetDatePicker (this.View);
			NSDate nsDate = (NSDate)DateTime.SpecifyKind (date, DateTimeKind.Utc);
			actionSheetDatePicker.DatePicker.Date = nsDate;
			actionSheetDatePicker.DatePicker.Mode = mode;
			actionSheetDatePicker.DatePicker.ValueChanged += valueChangedHandler;
			actionSheetDatePicker.Show ();
		}

		private void SubmitForm()
		{
			try {
				Client client = AuthenticationHelper.GetClient ();
				if (TimesheetId > 0)
					client.TimesheetService.UpdateTimesheet (timesheet);
				else
					client.TimesheetService.AddTimesheet (timesheet);
				hasErrors = false;
			} catch (CntResponseException ex) {
				hasErrors = true;
				Utility.ShowError (ex);
			}
		}

		private void SetUpKeyboardNotifications ()
		{
			NSNotificationCenter.DefaultCenter.AddObserver (UIKeyboard.DidShowNotification, KeyboardOpened);
			NSNotificationCenter.DefaultCenter.AddObserver (UIKeyboard.DidHideNotification, KeyboardClosed);
		}

		private void KeyboardOpened (NSNotification notification)
		{
			System.Console.WriteLine ("Keyboard Opened");
			UIView activeView = KeyboardGetActiveView();
			if (activeView == null)
				return;

			var keyboardFrame = UIKeyboard.FrameBeginFromNotification (notification);
			var contentInsets = new UIEdgeInsets (0.0f, 0.0f, keyboardFrame.Height, 0.0f);

			newTimesheetScrollView.ContentInset = contentInsets;
			newTimesheetScrollView.ScrollIndicatorInsets = contentInsets;

			// Position of the active field relative inside the scroll view
			RectangleF relativeFrame = activeView.Superview.ConvertRectToView(activeView.Frame, newTimesheetScrollView);
			var spaceAboveKeyboard = newTimesheetScrollView.Frame.Height - keyboardFrame.Height;

			// Move the active field to the center of the available space
			var offset = relativeFrame.Y - (spaceAboveKeyboard - activeView.Frame.Height) / 2;
			newTimesheetScrollView.ContentOffset = new PointF(0, offset);
		}

		private void KeyboardClosed (NSNotification notification)
		{
			System.Console.WriteLine ("Keyboard Closed");
			newTimesheetScrollView.ContentInset = UIEdgeInsets.Zero;
			newTimesheetScrollView.ScrollIndicatorInsets = UIEdgeInsets.Zero;
		}

		protected virtual UIView KeyboardGetActiveView()
		{
			return this.View.FindFirstResponder();
		}

		private void WireUpView ()
		{
			resetButton.Clicked += ResetButtonClicked;
			actionButton.TouchUpInside += ActionButtonClicked;

			startButton.TouchUpInside += StartButtonClicked;
			endButton.TouchUpInside += EndButtonClicked;

			//startTimeButton.TouchUpInside += StartTimeClicked; // Doesn't work because of timezone issues.
			startTimeUpButton.TouchUpInside += StartTimeUpClicked;
			startTimeDownButton.TouchUpInside += StartTimeDownClicked;
			//endTimeButton.TouchUpInside += EndTimeClicked; // Doesn't work because of timezone issues.
			endTimeUpButton.TouchUpInside += EndTimeUpClicked;
			endTimeDownButton.TouchUpInside += EndTimeDownClicked;

			recapTextView.Started += (object sender, EventArgs e) => {
				if (recapTextView.Text == "Tap to add recap...")
					recapTextView.Text = String.Empty;
			};
			recapTextView.Changed += (object sender, EventArgs e) => timesheet.Description = recapTextView.Text;
		}
		#endregion
	}
}
