// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using Cnt.API;
using Cnt.API.Exceptions;
using Cnt.Web.API.Models;

namespace Cnet.iOS
{
	// TODO: Figure out timezone stuff.
	// TODO: Properly wire up time up and down buttons.
	// TODO: Add mobile-side validation.
	public partial class OSNewTimesheetViewController : UIViewController
	{
		#region Private Members
		private static NSString timesheetListSegueName = new NSString ("TimesheetList");
		private const string dateFormat = "ddd, MMM d, yyyy";
		private const string timeFormat = "h:mm tt";
		private Timesheet timesheet;
		private bool hasErrors;
		#endregion

		public int PlacementId { get; set; }
		public int TimesheetId{ get; set; }

		public OSNewTimesheetViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			LoadTimesheet ();
			RenderTimesheet ();
		}

		public override bool ShouldPerformSegue (string segueIdentifier, NSObject sender)
		{
			if (segueIdentifier == timesheetListSegueName)
				return !hasErrors;

			return base.ShouldPerformSegue (segueIdentifier, sender);
		}

		#region Event Delegates
		private void ActionButtonClicked (object sender, EventArgs e)
		{
			SubmitForm ();
			if (!hasErrors)
				PerformSegue (timesheetListSegueName, this);
		}

		private void EndButtonClicked (object sender, EventArgs e)
		{
			ShowDatePicker (timesheet.End, UIDatePickerMode.Date, (object s, EventArgs ev) => {
				DateTime date = DateTime.SpecifyKind ((s as UIDatePicker).Date, DateTimeKind.Unspecified);
				timesheet.End = date;
				endLabel.Text = date.ToLocalTime().ToString (dateFormat);
			});
		}

		private void EndTimeDownClicked (object sender, EventArgs e)
		{
			ShowDatePicker (timesheet.End, UIDatePickerMode.Time, (object s, EventArgs ev) => {
				DateTime date = DateTime.SpecifyKind ((s as UIDatePicker).Date, DateTimeKind.Unspecified);
				TimeSpan time = new TimeSpan (date.Hour, date.Minute, date.Second);
				timesheet.End = timesheet.End.Date + time;
				endTimeLabel.Text = date.ToLocalTime().ToString (timeFormat);
			});
		}

		private void EndTimeUpClicked (object sender, EventArgs e)
		{
			ShowDatePicker (timesheet.End, UIDatePickerMode.Time, (object s, EventArgs ev) => {
				DateTime date = DateTime.SpecifyKind ((s as UIDatePicker).Date, DateTimeKind.Unspecified);
				TimeSpan time = new TimeSpan (date.Hour, date.Minute, date.Second);
				timesheet.End = timesheet.End.Date + time;
				endTimeLabel.Text = date.ToLocalTime().ToString (timeFormat);
			});
		}

		private void ResetButtonClicked (object sender, EventArgs e)
		{
			ResetForm ();
		}

		private void StartButtonClicked (object sender, EventArgs e)
		{
			ShowDatePicker (timesheet.Start, UIDatePickerMode.Date, (object s, EventArgs ev) => {
				DateTime date = DateTime.SpecifyKind ((s as UIDatePicker).Date, DateTimeKind.Unspecified);
				timesheet.Start = date;
				startLabel.Text = date.ToLocalTime().ToString (dateFormat);
			});
		}

		private void StartTimeDownClicked (object sender, EventArgs e)
		{
			ShowDatePicker (timesheet.Start, UIDatePickerMode.Time, (object s, EventArgs ev) => {
				DateTime date = DateTime.SpecifyKind ((s as UIDatePicker).Date, DateTimeKind.Unspecified);
				TimeSpan time = new TimeSpan (date.Hour, date.Minute, date.Second);
				timesheet.Start = timesheet.Start.Date + time;
				startTimeLabel.Text = date.ToLocalTime().ToString (timeFormat);
			});
		}

		private void StartTimeUpClicked (object sender, EventArgs e)
		{
			ShowDatePicker (timesheet.Start, UIDatePickerMode.Time, (object s, EventArgs ev) => {
				DateTime date = DateTime.SpecifyKind ((s as UIDatePicker).Date, DateTimeKind.Unspecified);
				TimeSpan time = new TimeSpan (date.Hour, date.Minute, date.Second);
				timesheet.Start = timesheet.Start.Date + time;
				startTimeLabel.Text = date.ToLocalTime().ToString (timeFormat);
			});
		}
		#endregion

		#region Private Methods
		private void LoadTimesheet ()
		{
			Client client = AuthenticationHelper.GetClient ();
			if (TimesheetId > 0)
				timesheet = client.TimesheetService.GetTimesheet (TimesheetId);
			else
				timesheet = new Timesheet () { 
					Created = DateTime.Now,
					Start = DateTime.Now,
					End = DateTime.Now.AddHours (1),
					PlacementId = PlacementId
				};
		}

		private void RenderTimesheet ()
		{
			resetButton.Clicked += ResetButtonClicked;
			actionButton.TouchUpInside += ActionButtonClicked;

			DateTime localStart = timesheet.Start.ToLocalTime ();
			DateTime localEnd = timesheet.End.ToLocalTime ();
			startLabel.Text = localStart.ToString (dateFormat);
			endLabel.Text = localEnd.ToString (dateFormat);
			startTimeLabel.Text = localStart.ToString (timeFormat);
			endTimeLabel.Text = localEnd.ToString (timeFormat);

			startButton.TouchUpInside += StartButtonClicked;
			endButton.TouchUpInside += EndButtonClicked;
			startTimeUpButton.TouchUpInside += StartTimeUpClicked;
			startTimeDownButton.TouchUpInside += StartTimeDownClicked;
			endTimeUpButton.TouchUpInside += EndTimeUpClicked;
			endTimeDownButton.TouchUpInside += EndTimeDownClicked;
		}

		private void ResetForm ()
		{
			// TODO: Reset form logic.
		}

		private void ShowDatePicker(DateTime date, UIDatePickerMode mode, EventHandler valueChangedHandler)
		{
			var actionSheetDatePicker = new ActionSheetDatePicker (this.View);
			NSDate nsDate = (NSDate)DateTime.SpecifyKind (date, DateTimeKind.Utc);
			actionSheetDatePicker.DatePicker.Date = nsDate;
			actionSheetDatePicker.DatePicker.Mode = mode;
			actionSheetDatePicker.DatePicker.ValueChanged += valueChangedHandler;
			actionSheetDatePicker.Show ();
		}

		private void SubmitForm()
		{
			try {
				Client client = AuthenticationHelper.GetClient ();
				if (TimesheetId > 0)
					client.TimesheetService.UpdateTimesheet (timesheet);
				else
					client.TimesheetService.AddTimesheet (timesheet);
				hasErrors = false;
			} catch (CntResponseException ex) {
				hasErrors = true;
				Utility.ShowError (ex);
			}
		}
		#endregion
	}
}
