// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Cnet.iOS
{
	public partial class OSNotificationsCell : UITableViewCell
	{
		public OSNotificationsCell (IntPtr handle) : base (handle)
		{
		}

		public UILabel FamilyNameLabel { get { return familyNameLabel; } set { familyNameLabel = value; } }
		public UILabel StatusLabel { get { return statusLabel; } set { statusLabel = value; } }
		public UILabel InfoLabel { get { return infoLabel; } set { infoLabel = value; } }
		public UIImageView ProfileImage { get { return profileImage; } set { profileImage = value; } }
		public UIImageView InfoImage { get { return infoImage; } set { infoImage = value; } }
		public UIButton CloseButton { get { return closeButton; } set { closeButton = value; } }
	}
}
