// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using MonoTouch.UIKit;
using Cnt.API;
using Cnt.Web.API.Models;
using MonoTouch.Foundation;

namespace Cnet.iOS
{
	public partial class OSProfileViewController : UIViewController
	{
		List<User> users;

		public OSProfileViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			Client client = AuthenticationHelper.GetClient ();
			users = new List<User> {client.UserService.GetUser(1)};
			//users.Add(client.UserService.GetUser(0)); // (client.PlacementService.GetPlacements ());
			this.profileTable.Source = new OSProfileTableSource (users);
		}

		public class OSProfileTableSource : UITableViewSource
		{
			private List<User> tableItems;
			static NSString OSProfileTableViewCellId = new NSString ("ProfileCellIdentifier");

			public OSProfileTableSource(List<User> items) : base()
			{
				tableItems = items;
			}

			public override int RowsInSection (UITableView tableview, int section)
			{
				return tableItems.Count;
			}

			public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
			{
				OSProfileCell cell = (OSProfileCell)tableView.DequeueReusableCell (OSProfileTableViewCellId, indexPath);
				cell.ProfileLabel.Text = "jennifersmith@gmail.com";
				cell.IconImage.Image = new UIImage ("icon-mail.png");
				cell.PhoneIconImage.Image = new UIImage ("icon-mobile-nocircle.png");

				return cell;
			}
		}
	}
}
