// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Cnet.iOS
{
	public partial class OSProfileCell : UITableViewCell
	{
		public OSProfileCell (IntPtr handle) : base (handle)
		{
		}
			
		public UILabel ProfileLabel{ get { return this.profileLabel; } set { this.profileLabel = value; } }
		public UIImageView IconImage { get { return this.iconImage; } set { this.iconImage = value; } }
		public UIImageView PhoneIconImage { get { return this.phoneIconImage; } set { this.phoneIconImage = value; } }
	}
}
