// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Cnet.iOS
{
	public partial class OSStartEndCell : UITableViewCell
	{
		public OSStartEndCell (IntPtr handle) : base (handle)
		{
		}

		public UILabel StartLabel { get { return startLabel; } set { startLabel = value; } }
		public UILabel EndLabel { get { return endLabel; } set { endLabel = value; } }
	}
}
