// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Cnet.iOS
{
	public partial class OSTimesCell : UITableViewCell
	{
		public OSTimesCell (IntPtr handle) : base (handle)
		{
		}

		public UILabel DateLabel { get { return dateLabel; } set { dateLabel = value; } }
		public UILabel TimeLabel { get { return timeLabel; } set { timeLabel = value; } }
	}
}
